pertopo_app/apis/apiConsultas/urls.py
from django.urls import path
from . import consultaProyectos

urlpatterns = [
    path('query_projects', consultaProyectos.query_projects, name='fill_project_table'),
    path('query_logbook', consultaProyectos.query_logbook, name='fill_logbook_table'),
]

pertopo_app/apis/apiFormularios/urls.py
from django.urls import path
from . import saveForms

urlpatterns = [
    path('save_add_task', saveForms.save_add_task, name='save_add_task'),
]

pertopo_app/apps/proyectos/urls.py
from django.urls import path
from . import views
from . import api_tables

urlpatterns = [
    path('', views.view_proyectos, name='index'),
    path('<int:project_id>/', views.view_proyecto_id, name='proyecto_id'),
    path('add', views.view_proyectos_add, name='add_project'),
]

pertopo_app/pertopo_app/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.proyectos.views import *

urlpatterns = [
    path('', admin.site.urls),
    path('proyectos/', include(('apps.proyectos.urls', 'apps.proyectos'), namespace='proyectos')),
    path('apiConsultas/', include(('apis.apiConsultas.urls', 'apis.apiConsultas'),
        namespace='apiConsultas')),
    path('apiFormularios/', include(('apis.apiFormularios.urls', 'apis.apiFormularios'),
        namespace='apiFormularios')),
]

pertopo_app/apps/proyectos/models.py
from django.db import models
from datetime import date

# Create your models here.
class Person(models.Model):
    name        = models.CharField(blank=False, max_length=100)
    last_name   = models.CharField(blank=False, max_length=100)
    phone       = models.CharField(blank=False, max_length=100)
    email       = models.CharField(blank=False, max_length=100)

    def __str__(self):
        return "%s %s" % (self.name, self.last_name)

class Custommer(models.Model):
    person  = models.ForeignKey(Person, on_delete=models.PROTECT,)
    address = models.CharField(blank=False, max_length=100)

class Project(models.Model):
    project_name                = models.CharField(blank=False, max_length=100)
    project_leader              = models.CharField(blank=False, max_length=100)
    project_address             = models.CharField(blank=False, max_length=100)
    project_city                = models.CharField(blank=False, max_length=100)
    project_seller              = models.CharField(blank=False, max_length=100)
    project_machine_operator    = models.CharField(blank=False, max_length=100)
    project_machine             = models.CharField(blank=False, max_length=100)
    project_custommer           = models.CharField(blank=False, max_length=100)
    project_start_date          = models.DateField(blank=False, max_length=100, default=date.today)
    project_end_date            = models.CharField(blank=True, max_length=100)
    project_estimate_meters     = models.CharField(blank=False, max_length=100)
    project_real_meters         = models.CharField(blank=True, max_length=100)
    project_price_per_meter     = models.CharField(blank=False, max_length=100)
    project_observations        = models.TextField(blank=True)
    project_progress            = models.CharField(blank=False, max_length=100, default='0')

    def __str__(self):
        return "%s" % (self.project_name)

class Logbooks(models.Model):
    project             = models.ForeignKey(Project, on_delete=models.PROTECT)
    log_date            = models.CharField(blank=False, default=date.today, max_length=100)
    log_task            = models.CharField(blank=False, default='NULL', max_length=100)
    log_meters          = models.CharField(blank=False, default='0', max_length=100)
    log_total_meters    = models.CharField(blank=False, default='0', max_length=100)

pertopo_app/apps/proyectos/forms.py
from django import forms
from .models import *

class ProjectForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = (
            'project_name',
            'project_leader',
            'project_address',
            'project_city',
            'project_seller',
            'project_machine_operator',
            'project_machine',
            'project_custommer',
            'project_start_date',
            'project_estimate_meters',
            'project_price_per_meter',
            'project_observations',
        )
        widgets = {
            'project_name': forms.TextInput(attrs={
                'class': 'form-control',
                'type': 'text',
            }),
            'project_leader': forms.TextInput(attrs={
                'class': 'form-control',
                'type': 'text',
            }),
            'project_address': forms.TextInput(attrs={
                'class': 'form-control',
                'type': 'text',
            }),
            'project_city': forms.TextInput(attrs={
                'class': 'form-control',
                'type': 'text',
            }),
            'project_seller': forms.TextInput(attrs={
                'class': 'form-control',
                'type': 'text',
            }),
            'project_machine_operator': forms.TextInput(attrs={
                'class': 'form-control',
                'type': 'text',
            }),
            'project_machine': forms.TextInput(attrs={
                'class': 'form-control',
                'type': 'text',
            }),
            'project_custommer': forms.TextInput(attrs={
                'class': 'form-control',
                'type': 'text',
            }),
            'project_start_date': forms.TextInput(attrs={
                'class': 'form-control',
                'type': 'text',
            }),
            'project_estimate_meters': forms.TextInput(attrs={
                'class': 'form-control',
                'type': 'text',
            }),
            'project_price_per_meter': forms.TextInput(attrs={
                'class': 'form-control',
                'type': 'text',
            }),
            'project_observations': forms.Textarea(

            attrs={
                'class': 'form-control',
                'type': 'text',
            }),
        }

class LogbookForm(forms.ModelForm):
    class Meta:
        model = Logbooks
        fields = (
            'project',
            'log_date',
            'log_task',
            'log_meters',
        )
        widget = {
            'log_date': forms.TextInput(attrs={
                'class': 'form-control',
                'type': 'text',
            }),
            'log_task': forms.TextInput(attrs={
                'class': 'form-control',
                'type': 'text',
            }),
            'log_meters': forms.TextInput(attrs={
                'class': 'form-control',
                'type': 'text',
            }),
        }

pertopo_app/apps/proyectos/views.py
from django.shortcuts import render_to_response, render

from apps.proyectos.models import *
from apps.proyectos.forms import *

# Create your views here.
def view_proyectos(request):
    template_name   = "pertopo/proyectos/index.html"
    form = LogbookForm()
    return render(request, template_name, {'form': form})

def view_proyecto_id(request, project_id):
    template_name   = "pertopo/proyectos/proyecto_id.html"
    by_id           = Project.objects.get(pk=project_id)
    context         = {'proyecto': by_id}
    return render_to_response(template_name, context)

def view_flash_message(request):
    return render(request, template_name)

def view_proyectos_add(request):
    template_name   = "pertopo/proyectos/add_project.html"

    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return view_proyectos(request)
        else:
            #return view_flash_message(request)
            print(form.errors)
    else:
        form = ProjectForm()

    context = {'form': form}

    return render(request, template_name, context)

def view_logout(request):
    template_name   = "pertopo/close_session.html"
    return render(request, template_name)

pertopo_app/templates/pertopo/close_session.html
{% extends "admin/base.html" %}

{% block content_container %}
aqui va lo de logout
{% endblock content_container %}

pertopo_app/templates/pertopo/proyectos/add_project.html
{% extends "pertopo/proyectos/index.html" %}
{% load i18n static %}

{% block inicio_app %}
  <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
   &rsaquo; <a href="{% url 'proyectos:index' %}">Proyectos</a>
{% endblock %}

{% block content_container %}
  <div class="col-lg-12">
    <div class="card card-info">
      <div class="card-header">
        <h3 class="card-title">Agregar nuevo proyecto</h3>
      </div>
      <!-- /.card-header -->
      <!-- form start -->

      <form class="form-vertical" method='POST'>{% csrf_token %}
        <div class="card-body">
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label for="id_project_name" class="control-label">Nombre del proyecto</label>
                {{ form.project_name}}
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label for="id_project_leader" class="control-label">Lider de proyecto</label>
                {{ form.project_leader }}
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label for="id_project_address" class="control-label">Lugar</label>
                <!--<input type="text" class="form-control" id="name">-->
                {{ form.project_address}}
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label for="id_project_city" class="control-label">Municipio</label>
                <!--<input type="text" class="form-control" id="name" placeholder="Segundo nombre">-->
                {{ form.project_city }}
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label for="id_project_seller" class="control-label">Quien hizo el trato</label>
                <!--<input type="text" class="form-control" id="name">-->
                {{ form.project_seller}}
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label for="id_project_machine_operator" class="control-label">Operador de máquina</label>
                {{ form.project_machine_operator }}
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label for="id_project_machine" class="control-label">Máquina</label>
                {{ form.project_machine }}
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label for="id_project_custommer" class="control-label">Cliente</label>
                {{ form.project_custommer }}
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label for="id_project_start_date" class="control-label">Fecha de inicio</label>
                {{ form.project_start_date}}
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label for="id_project_estimate_meters" class="control-label">Metros estimados</label>
                {{ form.project_estimate_meters}}
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label for="id_project_start_date" class="control-label">Precio por metro</label>
                {{ form.project_price_per_meter}}
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label for="id_project_observations" class="control-label">Observaciones</label>
                {{ form.project_observations}}
              </div>
            </div>
          </div>
          <br><br>
          <div class="row">
            <div class="col-md-8"></div>
            <div class="col-md-2">
              <div class="form-group">
                <input class="btn btn-success" type="submit" value="Guardar">
              </div>
            </div>
            <div class="col-md-2">
              <div class="form-group">
                <input class="btn btn-danger" type="button" value="Cancelar">
              </div>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock content_container %}

pertopo_app/templates/pertopo/proyectos/index.html
{% extends "admin/base.html" %}
{% load i18n static %}
{% block title %}Pertopo | Proyectos{% endblock %}

{% block inicio_app %}
  <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
   &rsaquo; Proyectos
{% endblock %}
{% block content_container %}
<div id='id_projects_main'>

  <div class="row" >
    <div class="col-12">
      <nav class="navbar navbar-expand bg-white navbar-light border-bottom">
        <ul class="navbar-nav">
          <li class="nav-item d-none d-sm-inline-block">
            <a href="" class="nav-link">Proyectos</a>
          </li>
        </ul>

        <!-- SEARCH FORM -->
        <form class="form-inline ml-3">
          <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Buscar proyectos" aria-label="Search">
            <div class="input-group-append">
              <button class="btn btn-navbar" type="submit">
                <i class="fa fa-search"></i>
              </button>
            </div>
          </div>
        </form>

        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">
          <!-- Agregar nuevo proyecto -->
          <li class="nav-item dropdown">
            <a class="nav-link" href="{% url 'proyectos:add_project' %}" id="show_add_project">
              <i class="fa fa-plus-square" title="Agregar nuevo proyecto"></i>
            </a>
          </li>
          <!-- Proyecto en curso -->
          <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
              <i class="fa fa-hourglass-start" title="Proyectos en curso"></i>
              <span class="badge badge-danger navbar-badge">3</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
              <div class="dropdown-divider"></div>
              <div class="dropdown-divider"></div>
              <div class="dropdown-divider"></div>
            </div>
          </li>
          <!-- Notificaciones -->
          <li class="nav-item dropdown">
          </li>
        </ul>
      </nav>
    </div>
  </div>
  <div class="row">
    <div class="container-fluid">
        <div class="col-12">
          <div>
            <div>
              <table class="table table-bordered" id="id_projects_table">
                <thead>
                  <tr>
                    <th style="width: 10px">#</th>
                    <th>Proyecto</th>
                    <th>Lider</th>
                    <th style="width: 40px">Avance</th>
                  </tr>
                <thead>
                <tbody>
                    <!-- fillProjectsTable -->
                </tbody>
              </table>
            </div>
          </div>

        </div>
    </div>
  </div>

</div> <!-- ./id_projects_main -->

<div id="id_project_sections" style="display:none;">

  <div class="row">
    <div class="col-12">
      <nav class="navbar navbar-expand bg-white navbar-light border-bottom">
        <ul class="navbar-nav">
          <li class="nav-item d-none d-sm-inline-block">
            <a href="" class="nav-link" id='id_project_title'>Proyecto: </a>
          </li>
        </ul>
      </nav>
    </div>
  </div>
  <br>
  <!-- Logbook section -->
  <div class="row">
    <div class="col-md-12">
      <div class="card bg-info-gradient" id='id_main_card_log_task'><!--bg-info-gradient-->
        <div class="card-header">
          <h5 class="card-title">Bitácora de avances</h5>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" id="id_minus_log_task"
              data-widget="collapse" data-toggle="tooltip">
              <i class="fa fa-minus"></i>
            </button>
            <div class="btn-group">
              <button type="button" class="btn btn-tool dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-wrench"></i>
              </button>
              <div class="dropdown-menu dropdown-menu-right" role="menu">
                <a href="#" class="dropdown-item" onclick="showModal('id_add_task_modal')">Agregar tarea<a/a>
              </div>
            </div>
          </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
          <div class="row">
            <table class="table table-bordered" id="id_logbook_table">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Fecha</th>
                  <th>Metros</th>
                  <th>Tareas</th>
                </tr>
              </thead>
              <tbody>
                <!-- fillLogbookTable() -->
              </tbody>
            </table>
          </div>
        </div>
        <div class="card-footer">
          <div class="row">
            <div class="col-sm-3 col-6">
            </div>
            <div class="col-sm-3 col-6">
            </div>
            <div class="col-sm-3 col-6">
            </div>
            <div class="col-sm-3 col-6">
              <div class="description-block">
                <span class="description-percentage text-warning" id="id_total_meters"></span>
                <h5 class="description-header"></h5>
                <span class="description-text">METROS TOTALES</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- ./Loogbook section -->

  <!-- Price to customer -->
  <div class="row">
    <div class="col-md-12">
      <div class="card bg-info-gradient" id='id_main_card_price_customer'><!--bg-info-gradient-->
        <div class="card-header">
          <h5 class="card-title">Precios de la perforación para el cliente</h5>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" id="id_minus_price_customer"
              data-widget="collapse" data-toggle="tooltip">
              <i class="fa fa-minus"></i>
            </button>
            <div class="btn-group">
              <button type="button" class="btn btn-tool dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-wrench"></i>
              </button>
              <div class="dropdown-menu dropdown-menu-right" role="menu">
                <a href="#" class="dropdown-item" onclick="showModal('id_price_customer_modal')">Agregar tarea<a/a>
              </div>
            </div>
          </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
          <div class="row">
            <table class="table table-bordered" id="id_logbook_table">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Fecha</th>
                  <th>Concepto y actividad</th>
                  <th>Metros</th>
                  <th>Maquina</th>
                  <th>P/P MT</th>
                  <th>Subtotal</th>
                </tr>
              </thead>
              <tbody>
                <!-- fillPriceToCustomerTable() -->
              </tbody>
            </table>
          </div>
        </div>
        <div class="card-footer">
          <div class="row">
            <div class="col-sm-3 col-6">
            </div>
            <div class="col-sm-3 col-6">
            </div>
            <div class="col-sm-3 col-6">
            </div>
            <div class="col-sm-3 col-6">
              <div class="description-block">
                <span class="description-percentage text-warning" id="id_total_meters"></span>
                <h5 class="description-header"></h5>
                <span class="description-text">TOTAL</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- ./Price to customer -->

</div> <!-- ./id_poject_sections -->

<!--- MODAL -->
<div class="modal" tabindex="-1" role="dialog" id="id_add_task_modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Agregar Tarea</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="post" id='id_form_add_task'>{% csrf_token %}
          <div class="form-group">
            <label for="id_log_date" class="control-label">Fecha</label>
            {{ form.log_date }}
          </div>
          <div class="form-group">
            <label for="id_log_meters" class="control-label">Metros</label>
            {{ form.log_meters }}
          </div>
          <div class="form-group">
            <label for="id_log_task" class="control-label">Nombre de Tarea</label>
            {{ form.log_task }}
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id='id_save_form_add_task'>Guardar</button>
        <button type="button" class="btn btn-secondary" id='id_close_add_task' data-dismiss="modal">Cancelar</button>
      </div>
    </div>
  </div>
</div>
<!-- ./MODAL -->
<script src="{% static 'adminlte/plugins/jquery/jquery.min.js' %}"></script>

<script>
  $(document).ready( function () {
    // Crear <tr> de id_projects_table
    fillProjectTable();
  });
</script>
{% endblock content_container %}

pertopo_app/templates/pertopo/proyectos/proyecto_id.html
{% extends "admin/base.html" %}
{% load i18n static %}
{% block title %}Pertopo | Proyectos{% endblock %}

{% block inicio_app %}
  <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
   &rsaquo; <a href="{% url 'proyectos:index' %}">Proyectos</a>
{% endblock %}


{% block content_container %}
<div class="row">
  <div class="col-12">
    <nav class="navbar navbar-expand bg-white navbar-light border-bottom">
      <ul class="navbar-nav">
        <li class="nav-item d-none d-sm-inline-block">
          <a href="" class="nav-link">Proyecto: {{proyecto}}</a>
        </li>
      </ul>
    </nav>
  </div>
</div>
<br>
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">Bitácora de avances</h5>

        <div class="card-tools">
          <button type="button" class="btn btn-tool" data-widget="collapse">
            <i class="fa fa-minus"></i>
          </button>
          <div class="btn-group">
            <button type="button" class="btn btn-tool dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-wrench"></i>
            </button>
            <div class="dropdown-menu dropdown-menu-right" role="menu">
              <a href="#" class="dropdown-item">Agregar tarea<a/a>
            </div>
          </div>
        </div>
      </div>
      <!-- /.card-header -->
      <div class="card-body">
        <div class="row">
          <table class="table table-bordered" id="id_logbook_table">
            <thead>
              <tr>
                <th>Fecha</th>
                <th>Metros</th>
                <th>Tareas</th>
              </tr>
            </thead>
            <tbody>
            </tbody>
          </table>
        </div>
      </div>
      <div class="card-footer">
        <div class="row">
          <div class="col-sm-3 col-6">
            <!-- /.description-block -->
          </div>
          <!-- /.col -->
          <div class="col-sm-3 col-6">
            <!-- /.description-block -->
          </div>
          <!-- /.col -->
          <div class="col-sm-3 col-6">
            <!-- /.description-block -->
          </div>
          <!-- /.col -->
          <div class="col-sm-3 col-6">
            <div class="description-block">
              <h5 class="description-header"></h5>
              <span class="description-text">METROS TOTALES</span>
            </div>
            <!-- /.description-block -->
          </div>
        </div>
        <!-- /.row -->
      </div>
      <!-- /.card-footer -->
    </div>
    <!-- /.card -->
  </div>
  <!-- /.col -->
</div>
<script src="{% static 'adminlte/plugins/jquery/jquery.min.js' %}"></script>
<script>
  $(document).ready(function () {
    fillLogbookTable();
  });
</script>
{% endblock content_container %}